@Api_HostAddress = http://localhost:1337



###
POST {{Api_HostAddress}}/vendors/7473ee24-54d2-48f4-8e84-d240d65e4b16/catalog
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImJvYi1zbWl0aCIsInN1YiI6ImJvYi1zbWl0aCIsImp0aSI6ImJhMmM2NjA0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDoxMzM3IiwibmJmIjoxNzMxMzYwOTkxLCJleHAiOjE3MzkzMDk3OTEsImlhdCI6MTczMTM2MDk5MiwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.HZ8FFO_0i-0crEn66hbaMq2yNrDYn8f0TQQAJ0NH5cg

{
   "name": "VS Code",
    "description": "An editor for programmers"  
}